### ISSUE TITLE
running index.js not creating function

### ISSUE THREAD

**Issue by ramonck** [lg/lambda-job#3]
Hey,
I'm trying to run your examples in index.js and it's not working.

I run as "node index.js" is there anything else to execute after your code? it seems it's not running anything after setting, it's not exporting to Lambda. Do I need to execute the export.handlers?

Best Regards,

**Comment by lg** [comment]
Hello Ramon. Oh, that script is run by AWS Lambda. You'll need to create this Lambda Function manually and then the index.js file needs to be in the zip you upload to Amazon. Closing this as it's not really bug on lambda-job. Thanks!
